services:
  hdfs-namenode:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: hdfs-namenode
    hostname: hdfs-namenode
    restart: always
    ports:
      - "9870:9870"
      - "9000:9000"
    env_file:
      - .env
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - ./hadoop/dfs/namenode:/hadoop/dfs/namenode
      - ./hadoop/config/core-site.xml:/etc/hadoop/core-site.xml
      - ./hadoop/config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
    healthcheck:
      test: ["CMD", "curl", "-f", "http://hdfs-namenode:9870/"]
      interval: 10s
      timeout: 5s
      retries: 3
    entrypoint: ["/bin/bash", "-c"]
    command: >
      "if [ ! -d /hadoop/dfs/namenode/current ]; then
         hdfs namenode -format -nonInteractive;
       fi;
       hdfs namenode"
    networks:
      - trino-network

  hdfs-datanode:
    image: apache/hadoop:${HADOOP_VERSION}
    container_name: hdfs-datanode
    hostname: hdfs-datanode
    restart: always
    ports:
      - "9864:9864"
    depends_on:
      hdfs-namenode:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - HADOOP_CONF_DIR=/etc/hadoop
      - HADOOP_HEAPSIZE=2048
    volumes:
      - ./hadoop/dfs/datanode:/hadoop/dfs/datanode
      - ./hadoop/config/core-site.xml:/etc/hadoop/core-site.xml
      - ./hadoop/config/hdfs-site.xml:/etc/hadoop/hdfs-site.xml
    command: ["hdfs", "datanode"]
    networks:
      - trino-network

  trino-coordinator:
    image: trinodb/trino:${TRINO_VERSION}
    container_name: "trino-coordinator"
    hostname: trino-coordinator
    networks:
      - trino-network
    env_file:
      - .env
    ports:
      - "8080:8080"
      - "8443:8443"
    volumes:
      - ./trino/coordinator/config.properties:/etc/trino/config.properties
      - ./trino/coordinator/log.properties:/etc/trino/log.properties
      - ./trino/coordinator/jvm.config:/etc/trino/jvm.config
      - ./trino/coordinator/node.properties:/etc/trino/node.properties
      - ./trino/coordinator/password-authenticator.properties:/etc/trino/password-authenticator.properties
      - ./trino/coordinator/password.db:/etc/trino/password.db
      - ./trino/coordinator/certs/clustercoord.pem:/etc/trino/clustercoord.pem
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/data/coordinator:/data/trino
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://trino-coordinator:8080/v1/info"]
      interval: 10s
      timeout: 5s
      retries: 3
      
  trino-worker:
    image: trinodb/trino:${TRINO_VERSION}
    container_name: "trino-worker"
    hostname: trino-worker
    networks:
      - trino-network
    env_file:
      - .env
    volumes:
      - ./trino/worker/config.properties:/etc/trino/config.properties
      - ./trino/worker/log.properties:/etc/trino/log.properties
      - ./trino/worker/jvm.config:/etc/trino/jvm.config
      - ./trino/worker/node.properties:/etc/trino/node.properties
      - ./trino/catalog:/etc/trino/catalog
      - ./trino/data/worker:/data/trino
    restart: always
    healthcheck:
      test: ["CMD", "curl", "-f", "http://trino-worker:8080/v1/info"]
      interval: 10s
      timeout: 5s
      retries: 3

  hive-mysql:
    image: mysql:${MYSQL_VERSION}
    container_name: hive-mysql
    hostname: hive-mysql
    restart: always
    ports:
      - "3306:3306"
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=metastore_db
      - MYSQL_USER=hive
      - MYSQL_PASSWORD=hive
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
    command: mysqld --default-authentication-plugin=caching_sha2_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
    volumes:
      - ./hive-mysql/data:/var/lib/mysql
    networks:
      - trino-network

  hive-metastore:
    image: apache/hive:${HIVE_VERSION}
    container_name: hive-metastore
    hostname: hive-metastore
    restart: always
    ports:
      - "9083:9083"
    env_file:
      - .env
    environment:
      - SERVICE_NAME=metastore
      - DB_DRIVER=mysql
      - HIVE_HOME=/opt/hive
    volumes:
      - ./hive-metastore/config/hive-site.xml:/opt/hive/conf/hive-site.xml
      - ./hive-metastore/lib/mysql-connector-j-8.2.0.jar:/opt/hive/lib/mysql-connector-j-8.2.0.jar
      - ./hive-metastore/entrypoint.sh:/entrypoint.sh
    networks:
      - trino-network
    depends_on:
      hive-mysql:
        condition: service_healthy
      hdfs-namenode:
        condition: service_healthy


networks:
  trino-network:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 9000
    ipam:
      config:
        - subnet: 172.15.0.0/16
